# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n4G8Of_J0QoMzn4QjaXCsFoz2O0E1HrF
"""

!git clone https://github.com/pjreddie/darknet.git

cd darknet

!make

#####!./darknet detector train_voc data/obj.data yolo-obj.cfg darknet53.conv.74

!wget https://pjreddie.com/media/files/yolov3.weights

!./darknet detect cfg/yolov3.cfg yolov3.weights "/content/drive/My Drive/IMG-20191004-WA0003.jpg"

import cv2

# path  
path = r'/content/drive/My Drive/IMG-20191004-WA0003.jpg'

# Reading an image in default mode 
image = cv2.imread(path)

# Window name in which image is displayed 
window_name = 'image'

# Using cv2.imshow() method  
# Displaying the image  
cv2_imshow(!./darknet detect cfg/yolov3.cfg yolov3.weights "/content/drive/My Drive/IMG-20191004-WA0003.jpg")

from google.colab.patches import cv2_imshow

from google.colab import drive
drive.mount('/content/drive')