# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bo2LRE8PdmRXgIrko9zJ6Wm1yMb0fWat
"""

from google.colab import drive
drive.mount('/content/drive')

!ls -la "/content/drive/My Drive/darknet-master"

!/usr/local/cuda/bin/nvcc --version

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/pjreddie/darknet.git
# %cd darknet

!ls

!git checkout feature/google-colab

!make

# Commented out IPython magic to ensure Python compatibility.
def imShow():
  import cv2
  import matplotlib.pyplot as plot
#   %matplotlib inline

  image = cv2.imread(path)
  height, width = image[:2]
  resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)

  fig = plot.gcf()
  fig.set_size_inches(18,10)
  plot.axis("off")

  plot.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plot.show()



def UPLOAD():
  from google.colab import files
  uploaded = files.upload()
  for name, data in uploaded.items():
    with open(name, "wb") as f:
      f.write(data)
      print('saved file', name)
def download(path):
  from google.colab import files
  files.downloaded(path)

!wget https://pjreddie.com/media/files/yolov3.weights

!./darknet detect cfg/yolov3.cfg yolov3.weights "/content/drive/My Drive/IMG-20191004-WA0003.jpg"

import cv2

!./darknet yolo test cfg/yolov3.cfg yolov3.weights /content/drive/My\ Drive/IMG-20191008-WA0029.jpg

img = cv2.imread("IMG-20191008-WA0029.jpg")

type(img)
import numpy

img_src = cv2.imread('/content/drive/My Drive/IMG-20191008-WA0029.jpg',0)
print (img_src)

import matplotlib.pyplot as plot

plot.imshow(img_src)

